"""Output formatter — results as readable Markdown."""

from __future__ import annotations

from sparks.state import SynthesisOutput


def format_output(result: SynthesisOutput, goal: str) -> str:
    """Format synthesis output as Markdown."""
    lines = []
    lines.append(f"# Cognitive Analysis Results\n")
    lines.append(f"**Goal**: {goal}\n")
    lines.append(f"**Confidence**: {result.confidence:.0%}")
    lines.append(f"**Coverage**: {result.coverage:.0%}")
    lines.append(f"**Rounds**: {result.rounds_completed}")
    lines.append(f"**Cost**: ${result.total_cost:.2f}")
    lines.append("")

    # ── Core Principles ──
    lines.append("---\n")
    lines.append("## Core Principles\n")

    for i, p in enumerate(result.principles, 1):
        lines.append(f"### Principle {i}: {p.statement}\n")
        lines.append(f"**Confidence**: {p.confidence:.0%}")
        if p.supporting_patterns:
            lines.append(f"**Supporting patterns**: {', '.join(p.supporting_patterns[:5])}")
        if p.counter_evidence:
            lines.append(f"**Counter-evidence**: {', '.join(e.snippet for e in p.counter_evidence[:3])}")
        lines.append("")

    # ── Analogies ──
    if result.analogies:
        lines.append("---\n")
        lines.append("## Structural Analogies\n")
        for a in result.analogies:
            lines.append(f"- **{a.current}** ↔ **{a.past_match}**")
            lines.append(f"  Mapping: {a.structural_mapping}")
            if a.prediction:
                lines.append(f"  Prediction: {a.prediction}")
            lines.append("")

    # ── Model Results ──
    if result.model_accuracy is not None:
        lines.append("---\n")
        lines.append("## Model Test\n")
        lines.append(f"**Cardboard model accuracy**: {result.model_accuracy:.0%}")
        lines.append("")

    # ── Contradictions ──
    unresolved = [c for c in result.contradictions if not c.resolved]
    if unresolved:
        lines.append("---\n")
        lines.append("## Unresolved Contradictions\n")
        for c in unresolved:
            lines.append(f"- {c.insight_a} **vs** {c.insight_b}")
        lines.append("")

    # ── Limitations ──
    if result.limitations:
        lines.append("---\n")
        lines.append("## Limitations\n")
        for lim in result.limitations:
            lines.append(f"- {lim}")
        lines.append("")

    # ── Thinking Process ──
    tp = result.thinking_process
    if tp:
        lines.append("---\n")
        lines.append("## Thinking Process\n")
        lines.append(f"- Observations: {tp.get('observations', 0)}")
        lines.append(f"- Patterns found: {tp.get('patterns', 0)}")
        lines.append(f"- Principles extracted: {tp.get('principles_before_synthesis', 0)}")
        lines.append(f"- Analogies drawn: {tp.get('analogies', 0)}")
        lines.append(f"- Contradictions found: {tp.get('contradictions', 0)}")
        lines.append(f"- Model tests run: {tp.get('model_tests', 0)}")
        if tp.get("key_insight"):
            lines.append(f"\n**Key Insight**: {tp['key_insight']}")
        lines.append("")

    lines.append("---\n")
    lines.append("*Generated by [Sparks](https://github.com/your/sparks) — 13 cognitive primitives for deep understanding.*")

    return "\n".join(lines)
